### ISSUE TITLE
Add a few more data fields under [extra] for URLs to match AppStream

### ISSUE THREAD

**Issue by 1peter10** [linuxphoneapps/linuxphoneapps.org#3]
These are the things that we should at least match:
~~~
<url type="homepage"></url>
<url type="bugtracker"></url>
<url type="donation"></url>
<url type="translate"></url>
~~~
Please feel free to comment with additional types of project specific URLs :-)

**Comment by 1peter10** [comment]
The above named URLs are added, if you can come up with more,  please share!

**Comment by petrisch** [comment]
What you are building is quite similar to the mobian app section right? Not as a critique its great to have both.
They have the app ID as well, but not shure if thats distro or install dependent.

I believe there is a entry in the .desktop file that figures out wheter to show itself on the desktop or only on mobile. I think you where writing about it as well, but I wasn't able to find it. That could be something as well. Well it will be customicable in the future, so maybe not a good idea, don't know...

**Comment by 1peter10** [comment]
I am building a more performant version with more information of what's currently at [https://linmobapps.frama.io](https://linmobapps.frama.io), which is distro independent.
Regarding the entry in the desktop file (here's my [blog post on that](https://linmob.net/phosh-0-12-app-drawer/))... It's not something I want to add, as this is a stop gab solution, it would have to be tracked manually and it's easy to fix. Also, some distributions have disabled the "two app drawers" feature, so... I really doubt it would be worth the effort.

**Comment by 1peter10** [comment]
Closing this for now and for this milestone.
