### ISSUE TITLE
dots in App URLs

### ISSUE THREAD

**Issue by 1peter10** [linuxphoneapps/linuxphoneapps.org#4]
It would be great to have dots in the App URLs so that App URLs match the App ID.
﻿
This might be impossible however, depending on what Zola allows here. Needs research!

**Comment by petrisch** [comment]
oh you have it already, I see 😂

**Comment by 1peter10** [comment]
Setting slugify.paths = "safe" as outlined on https://www.getzola.org/documentation/content/page/#output-paths might help here.

**Comment by 1peter10** [comment]
Fixed.
